version: '3'
services: 
    nextjs:
        build: .
        container_name: nextjs-container
        volumes: 
            - ./app:/usr/src/app
        command: "yarn dev"
        ports:
            - "4001:3000"